### ISSUE TITLE
`delete_on_failure` is read from the wrong parameter level

### ISSUE THREAD

**Issue by friegger** [ljfranklin/terraform-resource#1]
The [documentation](https://github.com/ljfranklin/terraform-resource/blob/master/README.md#parameters) mentions the `delete_on_failure` property lives on the top level, but actually it has to be put under the `terraform` parameter.

https://github.com/ljfranklin/terraform-resource/blob/25b43fc9356e6032553741156305d786e33aac98/out/out.go#L93

**Comment by ljfranklin** [comment]
Hey @friegger, I recently un-nested the `terraform` properties to remove some of this confusion. Current README should be accurate now. Thanks for the feedback!
