### ISSUE TITLE
Git Version on terraform-resource docker image is affected by CVE

### ISSUE THREAD

**Issue by JenGoldstrich** [ljfranklin/terraform-resource#101]
Hello!

While verifying that nothing in my team's pipeline was affected by the recent Git CVE (https://gitlab.com/gitlab-com/gl-security/disclosures/blob/master/003_git_submodule/advisory.md#git-submodule-update-command-execution) we noticed that this resource has a affected git version in it
```
$ docker images
REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
ljfranklin/terraform-resource   latest              ed196f508bb7        13 days ago         147MB

$ docker run -it ed196f508bb7 bash
$ # git version
git version 2.22.0
```

Thank you!
Jenna Goldstrich and @a-b

**Comment by ljfranklin** [comment]
Thanks for the heads up @JenGoldstrich and @a-b! The `latest` resource image should now contain an updated `git` binary:

```
docker run -it ljfranklin/terraform-resource:latest git --version
git version 2.24.1
```

Closing this out as fixed, but I should set up some sort of security scanner for these images. Were y'all using some automated tool/service to find vulnerabilities in a given docker image?

**Comment by a-b** [comment]
We found it by manually. Automated scanner makes perfect sense.
