### ISSUE TITLE
Terragrunt Support

### ISSUE THREAD

**Issue by PurpleBooth** [ljfranklin/terraform-resource#104]
We use terragrunt to deduplicate some of our terraform. I had a look through the codebase and it seems pretty easy for me to add in support for it.

Do you think that this would be a good fit for a feature for this project? If so I'll submit a PR

My rough plan was:
1. Introduce new config option to the source "terragrunt"
2. Introduce parameter to `NewClient` with path to terraform executable, terragrunt uses terragrunt rather than terraform.
3. Add terragrunt to the docker image

I will use another approach if this isn't something you think is a good fit for this resource though.

**Comment by haploeco** [comment]
We use terragrunt as well, and I feel this would be a nice addition

**Comment by ljfranklin** [comment]
@PurpleBooth I'd be open to a PR which uses the approach you described. Here's a few additional concerns that come to mind that would need to be addressed:

- Adding an auto-bump-terragrunt job to CI similar to this: https://github.com/ljfranklin/terraform-resource/blob/4bf4e594d6846ef0e3fef69cc06d0afe566983cc/ci/pipeline.yml#L18-L41
- The resource currently manages the remote statefile by generating the `-backend-config` file [here](https://github.com/ljfranklin/terraform-resource/blob/4bf4e594d6846ef0e3fef69cc06d0afe566983cc/src/terraform-resource/terraform/client.go#L92-L108). If a user tries to use Terragrunt's [remote_state](https://terragrunt.gruntwork.io/docs/features/keep-your-remote-state-configuration-dry/#filling-in-remote-state-settings-with-terragrunt) feature I imagine they'll get some confusing errors or unexpected behavior. We could note in the README that `remote_state` is not supported, or stretch goal of raising an error if terragrunt.hcl contains the remote_state key.
- Just to confirm, we're not talking about supporting the terragrunt-only commands like `apply-all` correct? Treating the `terragrunt` binary as a drop-in replacement for the `terraform` binary as you described above sounds fine.

**Comment by PurpleBooth** [comment]
Just as a drop in replacement for terraform

**Comment by PurpleBooth** [comment]
Unfortunately, this is more work than I can manage at the moment. I might get time in a few months time, I'll close this for now.

Thanks for maintaining this amazing resource @ljfranklin! I really appreciate the work you do here and we use it a lot!

**Comment by acarsercan** [comment]
Anyone got this working? or using terragrunt with concourse?
