### ISSUE TITLE
Store plan logs to file

### ISSUE THREAD

**Issue by bartlettt** [ljfranklin/terraform-resource#105]
I think it would be really helpful if there was an option to store the plan logs to a file. That way the logs could be added to a PR as a comment, to assist with reviews.

**Comment by ljfranklin** [comment]
@bartlettt Your use case sounds reasonable, but I'm not sure this functionality should live in this resource. This seems like a general use case that could be useful across many resource types and shouldn't require re-implementation in each individual resource.

Could you open an issue on github.com/concourse/concourse to see if the Concourse team has any thoughts on how you could approach this? The first thing that comes to mind is writing a task that calls `fly watch` to get the build logs from a given job, not sure if there's an easy way to get the build number.

**Comment by bartlettt** [comment]
Agreed, I've opened an issue here: https://github.com/concourse/concourse/issues/5243
