### ISSUE TITLE
plan_only does not generate new resource version

### ISSUE THREAD

**Issue by tormath1** [ljfranklin/terraform-resource#111]
Hi,
### behavior
we are using a Terraform `plan` followed by a Terraform `apply`. `apply` should be triggered by the `plan`:
```yaml
          - get: tfstate
            passed:
              - terraform-plan
```
but it's **not** the case. Following concourse [documentation](https://concourse-ci.org/jobs.html#schema.step.get-step.trigger)

> [...] If [trigger] set to true, new builds of the job will be automatically created when a new version for this input becomes available.

`plan_only` does not generate a new version of the output since it does not generate a `serial` number like the `plan_run`.

### expected

`apply` job should should be triggered automatically after the `plan` job 

### version
```yaml
      repository: ljfranklin/terraform-resource
      tag: 0.12.17
```

**Comment by ljfranklin** [comment]
Good catch, looks like a bug. [This commit](https://github.com/ljfranklin/terraform-resource/commit/58ff3e3d6d3b7e3b6946cd5e6c2668c41cf66cfe) should address the problem by adding a `plan_checksum` field to the version. This change is now present on the `ljfranklin/terraform-resource:latest` and `ljfranklin/terraform-resource:0.12.24` images. Please let me know if that fixes the issue on your end.

**Comment by tormath1** [comment]
Hi @ljfranklin, it works as expected on 0.12.24. Thanks for your reactivity, have a good week.
