### ISSUE TITLE
Include terraform version as label on docker image

### ISSUE THREAD

**Issue by spire-allyjweir** [ljfranklin/terraform-resource#127]
Hi there,

First off, I'd like to thank you for the work you do in maintaining this project. My team are using it extensively and it has helped us build a GitOps workflow for auto-applying Terraform really nicely. Thanks 😄 

## Problem
We have a Concourse pipeline that triggers whenever a new version of this project is released to Docker Hub under the latest tag. Once we have the image, we need to retrieve the version of `terraform` installed using a messy 'docker-in-docker' model. 

## Proposed Solution
Ideally the version of `terraform` would be included as a `LABEL` on the Dockerfile and thus retrievable via the `docker-inspect.json` file made available after retrieving an image via the `docker-image-resource` resource type instead of having to parse it out of a running instance of the container image.

## Context
We actually use your image as a base and add a couple extra binaries to support some `local-exec`-ing we do within some specific Terraform. A bit of an anti-pattern I know but it lets us manage our Concourse users and teams via Terraform which is nice, using `local-exec` with `fly`.

We have a Concourse pipeline which triggers whenever a new version of the docker image is released with the `latest` tag. We match on this to avoid the `dev` tag which changes regularly.

In that pipeline, we need to extract out the version of `terraform` in the image so that we can tag and label our downstream image with the correct version. Currently we have to run this to extract that value:

```bash
TAG="$(docker run --entrypoint=/bin/ash ljfranklin/terraform-resource:latest -c 'terraform --version | head -n 1 | cut -c 12-')"
```

## Next Steps
If you'd be keen for this I'd be happy to cut a PR with the changes.

**Comment by ljfranklin** [comment]
PR sounds good to me. Dockerfile is [here](https://github.com/ljfranklin/terraform-resource/blob/master/docker-prod/Dockerfile) and you should be able to get the version from [this file](https://github.com/ljfranklin/terraform-resource/blob/master/config/terraform-version).

**Comment by spire-allyjweir** [comment]
Thanks, I'll try get to this at some point this week.

**Comment by ljfranklin** [comment]
Closed via https://github.com/ljfranklin/terraform-resource/pull/129
