### ISSUE TITLE
glibc bindings from `libc6-compat` are weaker than needed for AWS cli

### ISSUE THREAD

**Issue by ships** [ljfranklin/terraform-resource#130]
Hi lyle, long time no see~~

I am doing some wacky stuff with `provisioner`s which need to invoke `aws` cli. AWS CLI requires glibc, but weirdly the libc6-compat shim still had issues linking. It seems [this alternative glibc shim](https://github.com/sgerrand/alpine-pkg-glibc/issues/51) works better -- but as that link shows, it is mutually exclusive with `libc6-compat`.

I followed [this dramatic thread](https://github.com/aws/aws-cli/issues/4685#issuecomment-615872019) to a solution which involved a pretty large bloat in my dockerfile, but it works. I would be happy to open a PR to this effect!

Two questions:
- is this something you would allow from a docker image bloat perspective? After all it may help other AWS users but only those.
- if so, would you accept using the alternative glibc binding?

**Comment by ljfranklin** [comment]
Hey Eve!

I've unfortunately run into this issue before on a [different project](https://github.com/ljfranklin/deployments/blob/aa5502b0cdc2290b476f5e1bb3ecac73e28f4729/ci/docker/Dockerfile#L13-L17). I'd be open to a PR that removes the `libc6-compat` package in favor of sgerrand's [glibc package](https://github.com/sgerrand/alpine-pkg-glibc). You'll have to update both the [dev](https://github.com/ljfranklin/terraform-resource/blob/master/docker-dev/Dockerfile) and [prod](https://github.com/ljfranklin/terraform-resource/blob/master/docker-prod/Dockerfile) images. The Terraform binaries were pretty huge last I checked so I doubt the image size will increase by a noticeable amount.
