### ISSUE TITLE
Support Terraform v0.14

### ISSUE THREAD

**Issue by kurtmc** [ljfranklin/terraform-resource#137]
Terraform v0.14 was just released: https://github.com/hashicorp/terraform/releases/tag/v0.14.0

I thought I would just create an issue for upgrading it so I can get notified when it's ready :smile:

I am also happy to do some testing on some of my existing pipelines before you push a release if you like.

**Comment by ljfranklin** [comment]
Done, had to make a couple small fixes but the updated images are now available: `ljfranklin/terraform-resource:latest` and `ljfranklin/terraform-resource:0.14.0`.
