### ISSUE TITLE
Release ARM64 Image

### ISSUE THREAD

**Issue by odidev** [ljfranklin/terraform-resource#140]
Hi,
I am trying to use terraform-resource image over ARM64v8 but it seems it does not have an arm64 supported tag in the [docker hub](https://hub.docker.com/r/ljfranklin/terraform-resource).

I have successfully built the [image ](https://hub.docker.com/repository/docker/odidev/terraform-resource/tags?page=1&ordering=last_updated) on arm64 platform by implementing [these ](https://github.com/odidev/terraform-resource/commit/dc58ab38bc26a25b82d7e3723d9a3fc5e8727e8c) changes.

**ARM64 Image:** https://hub.docker.com/repository/docker/odidev/terraform-resource/tags
**Changes required:** https://github.com/odidev/terraform-resource/commit/dc58ab38bc26a25b82d7e3723d9a3fc5e8727e8c

Do you have any plans for releasing an ARM64 image?

May I know how the amd64 image is getting published on Docker hub?

If interested, I will raise a PR.

**Comment by ljfranklin** [comment]
I'm definitely interested, trying out Concourse on a Raspberry Pi has been on my TODO list for a while. And thanks for the [PR](https://github.com/ashald/terraform-provider-stateful/pull/3) adding an ARM64 build for the stateful Terraform plugin!

I think the main complication is getting the [glibc alpine package](https://github.com/ljfranklin/terraform-resource/blob/ff61d03e78b04da6fce6ff152e7490bdc0e67f28/docker-prod/Dockerfile#L6-L9) installed on an ARM64 system. Currently looks like that package is [x86_64 only](https://github.com/sgerrand/alpine-pkg-glibc/blob/a266c5d8a45750e0b416382078978e7b0f2d5ebb/APKBUILD#L8). Some users have reported issues with certain Terraform providers requiring glibc, although your image may work fine for your use case. As it stands, I think getting that glibc package updated to build on ARM64 would be a blocker. I like to stick with an alpine base image if at all possible, although switching to something like ubuntu/debian is an option.

**Comment by ljfranklin** [comment]
Good news, we now have an ARM64 image available:

```
$ docker run --platform linux/arm64 -it ljfranklin/terraform-resource:latest uname -m
aarch64
```

Give it a try and let me know if you run into any issues. My Concourse deployment runs on x86 so I haven't tested the ARM64 image other than ensuring it builds cleanly.

For reference, here are [the changes](https://github.com/ljfranklin/terraform-resource/compare/681e43cac3650cdc062e1f996adbbf584dd3b595..7ac55ae33ed6665ef6a939d84555b50f2834fd42) required to get it working. Also seemed like the docker-buildx-resource isn't really maintained. Seems like a large amount of work to get all the other popular Concourse resource types built for ARM64 unfortunately.
