### ISSUE TITLE
Show commit SHA and/or terraform version in version json

### ISSUE THREAD

**Issue by ctaymor** [ljfranklin/terraform-resource#15]
It could be useful for debugging purposes to know the version of the terraform-resource and/or of terraform cli.

**Comment by ljfranklin** [comment]
@ctaymor not sure what you mean by "version json". The version of Terraform that gets bundled into the Docker image is pulled from [this file](https://github.com/ljfranklin/terraform-resource/blob/master/config/terraform-version) if that helps.

**Comment by ctaymor** [comment]
We saw that (at least on successful runs) concourse outputs some metadata that you seem to control. When we thought we were running into an issue with the terraform version, @coreyti and I thought this would be helpful to see in that metadata, for debugging.
![screen shot 2016-11-22 at 8 55 41 am](https://cloud.githubusercontent.com/assets/4574361/20533278/cd064468-b091-11e6-8184-6a0671b3b554.png

**Comment by ljfranklin** [comment]
@ctaymor the `latest` resource image now includes the output of `terraform -v` in the Resource Metadata. Thanks for the feedback!

![screen shot 2016-12-03 at 2 13 36 pm](https://cloud.githubusercontent.com/assets/1923644/20862558/dc9f15b0-b962-11e6-8047-ae033947445b.png)

**Comment by ctaymor** [comment]
Thanks @ljfranklin.
