### ISSUE TITLE
Support module local file paths

### ISSUE THREAD

**Issue by friegger** [ljfranklin/terraform-resource#17]
Currently, the resource does not support local file paths as described here:
https://www.terraform.io/docs/modules/sources.html

**Comment by ljfranklin** [comment]
@friegger sorry for letting this sit, I'll try get this fixed in the next couple days.

**Comment by ljfranklin** [comment]
@friegger This should be fixed in the `latest` image. Please give it a spin and re-open if it doesn't fit your use case.
