### ISSUE TITLE
Ability to specify state locking timeout

### ISSUE THREAD

**Issue by antonysouthworth-halter** [ljfranklin/terraform-resource#170]
Terraform provides the [`-lock-timeout`](https://www.terraform.io/cli/commands/apply#lock-timeout-duration) flag to allow waiting for the lock if it's already been acquired, instead of immediately aborting the operation with status code 1.

It would be handy if this resource provided a similar `lock-timeout` parameter, it could simply forward the argument to the `-lock-timeout` flag to Terraform.

Example step usage: wait up to 30 seconds for the lock

```yaml
- put: terraform
  params:
    lock-timeout: 30s
```

**Comment by ljfranklin** [comment]
Sounds reasonable, added the "help wanted" tag if you or someone else wants to contribute this feature.
