### ISSUE TITLE
Pushing variables in environment

### ISSUE THREAD

**Issue by Seraf** [ljfranklin/terraform-resource#18]
Hello @ljfranklin,

I have a problem with a remote state provider on S3. To access it, i have to provide my access/secret keys which will be stored in the remote state.
The aws sdk use by default variables stored in the environment.

Do you think it's possible to add an env parameter to push keys/values in the resource environment ?

**Comment by ljfranklin** [comment]
@Seraf not sure what you mean by "stored in the remote state". Your storage creds are not stored in any state files, they are only stored in the Concourse database along with the rest of the pipeline config.

**Comment by Seraf** [comment]
@ljfranklin : i'm talking about this : https://www.terraform.io/docs/state/remote/s3.html

"Note: Passing credentials directly via configuration options will make them included in cleartext inside the persisted state. Use of environment variables or a configuration file is recommended."

**Comment by ljfranklin** [comment]
@Seraf I understand now, the Resource does not use the built-in TF remote state file storage. Instead, the resource uses the AWS SDK directly to upload and download the statefile. So no AWS creds are stored in the statefile.

**Comment by Seraf** [comment]
@ljfranklin : it's true for the remote storage of the sources we are applying, but we may access other remote state in our files.
For example, all my vpc, network etc is stored in a remote state named infrastructure. So I import and use it on all my terraform sources.
I need to access these remote state from terraform. Actually it works using a config hash in the terraform files, but as indicated in the docs it should be better to rely on the environment.

That's why I opened an issue to suggest a way to inject custom env variable as it seems that terraform use sdk that rely on these variables.

**Comment by xlr-8** [comment]
Hello @ljfranklin,

The problem is when using other remote states, e.g.:
```bash
data "terraform_remote_state" "infrastructure" {
  backend = "s3"
  config {
    bucket     = "terraform-remote-state"
    key        = "infrastructure/terraform.tfstate"
    region     = "eu-west-1"
  }
}

data "terraform_remote_state" "iam" {
  backend = "s3"
  config {
    bucket     = "cycloid-terraform-remote-state"
    key        = "iam/terraform.tfstate"
    region     = "eu-west-1"
  }
}
```

This would no work, and would end up creating:
```
data.template_file.user_data: Refreshing state...
data.terraform_remote_state.infrastructure: Refreshing state...
data.terraform_remote_state.iam Refreshing state...
Error refreshing state: 1 error(s) occurred:

* data.terraform_remote_state.infrastructure: AccessDenied: Access Denied
	status code: 403, request id: XXXXXXXXXXXXXX
* data.terraform_remote_state.iam: AccessDenied: Access Denied
	status code: 403, request id: XXXXXXXXXXXXXX
```

In order to fix this, then the provider file would have to be modified to have:
```bash
data "terraform_remote_state" "infrastructure" {
  backend = "s3"
  config {
    bucket     = "terraform-remote-state"
    key        = "infrastructure/terraform.tfstate"
    region     = "eu-west-1"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
  }
}

data "terraform_remote_state" "iam" {
  backend = "s3"
  config {
    bucket     = "terraform-remote-state"
    key        = "iam/terraform.tfstate"
    region     = "eu-west-1"
    access_key = "${var.access_key}"
    secret_key = "${var.secret_key}"
  }
}
```

And thus exposing the `access_key` & `secret_key` in the tfstate. Maybe there is a better solution/trick, but haven't found it.

Thanks for your help,

**Comment by ljfranklin** [comment]
@Seraf okay I actually understand now :) I didn't know you could use the State File as a resource: https://www.terraform.io/docs/providers/terraform/d/remote_state.html. The real problem is Terraform shouldn't be storing creds in the state file, but looks like this is a known issue: https://github.com/hashicorp/terraform/issues/516. Adding configurable env variables sounds reasonable, and I've seen other providers that optionally take environment variables.

**Comment by ljfranklin** [comment]
@Seraf Just added `source.env` and `put.params.env` to the resource. Give those a try and re-open this issue if you find any problems.

**Comment by xlr-8** [comment]
hello @ljfranklin,

Unfortunately it doesn't work for me. Maybe I missed something?

My provider files look like:
```yaml
data "terraform_remote_state" "infrastructure" {
  backend = "s3"
  config {
    bucket     = "terraform-remote-state"
    key        = "env/terraform.tfstate"
    region     = "eu-west-1"
  }
}

data "terraform_remote_state" "iam" {
  backend = "s3"
  config {
    bucket     = "terraform-remote-state"
    key        = "other-env/terraform.tfstate"
    region     = "eu-west-1"
  }
}

provider "aws" {
  access_key = "${var.access_key}"
  secret_key = "${var.secret_key}"
  region     = "${var.aws_region}"
}
```

I have tried with various options according to https://www.terraform.io/docs/providers/aws/:
```yaml
      env:
       # Capital with region (despite region being in the provider.tf)
       AWS_ACCESS_KEY_ID: yyyyyyyyy
       AWS_DEFAULT_REGION: eu-west-1
       AWS_SECRET_ACCESS_KEY: xxxxxxx
       # just like the params
       access_key: yyyyyyyyy
       secret_key: xxxxxxx
       # just like capital but lower-case
       aws_secret_access_key_id: xxxxxxx
       aws_access_key_id: yyyyyyyyy
```

Is there something obvious that I missed, I also added the region just in case, but no luck either.
Re-adding the credentials in the provider file, works like a charm.

Thanks!

**Comment by Seraf** [comment]
Works perfectly, thanks !
