### ISSUE TITLE
Plan fails due to the size when uploading to backend

### ISSUE THREAD

**Issue by virtualguy** [ljfranklin/terraform-resource#183]
When the plan becomes very large (exceeds 4MB) the plan fails with the below message

```
023/02/22 09:53:26 Plan Error: Failed to upload plan file to TF backend. Use `fly intercept` to SSH into this container and view /tmp/tf-plan.log for more logs. Error: Failed to run Terraform command: exit status 1
```

Happy to diagnose or provide further logs as required

**Comment by ljfranklin** [comment]
Sorry for the delayed response. Sounds like a duplicate of https://github.com/ljfranklin/terraform-resource/issues/165. But you should follow the steps listed in the error message and see what `/tmp/tf-plan.log` contains to know for sure.
