### ISSUE TITLE
Feature Request: Loads vars from Terraform output JSON

### ISSUE THREAD

**Issue by DanielJonesEB** [ljfranklin/terraform-resource#25]
Just came across this need on a project, and raising it here so we don't forget in case we get time to do a PR.

It'd be good if we could use a file containing `terraform output -json` instead of the `vars` element in a put. We've got dependent Terraform steps in different jobs, so we could put the output in one job, and then get it as part of a later plan and then pick up all of those vars just by specifying the path to where that get was mounted in the container.

**Comment by ljfranklin** [comment]
@DanielJonesEB any issues with using `put.params.var_file: prev-terraform-put/metadata`? The `metadata` file is just a flattened version of `terraform output -json` and `var_file` is like `var` but reads a list of vars from a file.

**Comment by DanielJonesEB** [comment]
Ah, sorry - too busy trying to keep up with a pair to read the docs properly :)
