### ISSUE TITLE
get and put of terraform resource should not show credentials

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [ljfranklin/terraform-resource#28]
Right now, a `get` on a terraform resource will dump out all the outputs, which may contain credentials (e.g. if I create an RDS resource, or an IAM user, I may want to output the creds so I can thread them through to a downstream job).  It would be great if these credentials were obfuscated, or perhaps the whole output could be obfuscated (might be hard to decide exactly where to draw the line on what to obfuscate, e.g. maybe some IPs should be obfuscated too?).  Ideally, this would happen by default, but at minimum there should be some way to opt into this obfuscation.

/cc @fushewokunze-pivotal

**Comment by ljfranklin** [comment]
@Amit-PivotalLabs @fushewokunze-pivotal did a bit of digging and terraform allows you to specify outputs as [sensitive](https://www.terraform.io/docs/configuration/outputs.html). Terraform ensures that these sensitive outputs will not be displayed as part of the "Outputs" section that prints in the build logs after the Apply.

Makes sense that the resource should respect this `sensitive` flag and redact those outputs in the metadata section that prints on the right hand side of the Concourse UI. The outputs would still show up un-redacted in the `metadata` file that the resource writes to disk. Sound reasonable?

**Comment by fushewokunze-pivotal** [comment]
@ljfranklin yes I think that will be ok.

**Comment by ljfranklin** [comment]
@fushewokunze-pivotal @Amit-PivotalLabs the `latest` docker image for this resource should now correctly hide `sensitive` outputs in the build logs. Give it a try and please re-open if something looks off.
