### ISSUE TITLE
Support for terraform overrides

### ISSUE THREAD

**Issue by adi-mishra** [ljfranklin/terraform-resource#34]
Are there any plans to support terraform overrides? https://www.terraform.io/docs/configuration/override.html

**Comment by ljfranklin** [comment]
@adi-mishra looks like if a file within the `terraform_source` directory is named `override.tf` or ends in `_override` then the resource should pick it up. Does this not work or are you trying to reference override files from outside the `terraform_source` directory?

**Comment by adi-mishra** [comment]
It does, its just that its not very elegant when fetching a git resource for terraform_source directory.

**Comment by ljfranklin** [comment]
@adi-mishra agreed, would be nicer if didn't have to copy the override file into the source repo. I'll re-open this for a while to see you if or someone else wants to take a stab at a PR.

**Comment by ljfranklin** [comment]
@adi-mishra finally had a use case for override files. The resource now supports `put.params.override_files`, please re-open if you run into issues with it.
