### ISSUE TITLE
Support for getting build information as terraform variables

### ISSUE THREAD

**Issue by divyabhargov** [ljfranklin/terraform-resource#36]
We have had a need to tag the instances that are spun out using terraform with the build information in order to trace and tie back the instances to the concourse build. The specific variables we need are already available in the Put container as environment variables. What do you think about having the following list available as terraform variables, similar to the env_name that is the only one currently provided ?

$BUILD_NAME
$BUILD_JOB_NAME
$BUILD_PIPELINE_NAME
$BUILD_ID
$BUILD_TEAM_NAME
$ATC_EXTERNAL_URL

The reason we cant use the concourse container environment variables directly is because in order for terraform to read environment variables they must be prefixed with TF_VAR_
https://www.terraform.io/intro/getting-started/variables.html#from-environment-variables

**Comment by ljfranklin** [comment]
@divyabhargov sounds useful. Would you be willing to submit a PR for this feature? You could add to list of variables similar to [this line](https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/out/out.go#L67), and add a test to `out_test.go`. A quick guide to running the tests is [here](https://github.com/ljfranklin/terraform-resource/blob/master/DEVELOPMENT.md). Going to mark this as open for contribution, let me know if you have questions.

**Comment by doty-pivotal** [comment]
We have a story in our backlog to do so.  Thanks for you help.

**Comment by divyabhargov** [comment]
@ljfranklin We are trying to figure out the testing setup. We would like to know your opinion if you think it is adequate test coverage if we just add  a test for fixtures/aws inside out_test.go ?

**Comment by ljfranklin** [comment]
@divyabhargov yep, that's fine. This project mostly relies on integration tests, so the unit testing is somewhat minimal.

**Comment by ljfranklin** [comment]
Fixed in https://github.com/ljfranklin/terraform-resource/pull/37
