### ISSUE TITLE
Terraform 0.10.0 has an incompatible change for `terraform init`

### ISSUE THREAD

**Issue by beyhan** [ljfranklin/terraform-resource#38]
As described [here](https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md) terraform 0.10.0 introduces with [this commit](https://github.com/hashicorp/terraform/commit/8a7a0a74597ce2edde783d706d8402ccfbb7101e) a backwards incompatible change for `terraform init`. This seems to brake the concourse resource because we see in our pipelines errors like:
```
Terraform initialized in an empty directory!

The directory has no Terraform configuration files. You may begin working
with Terraform immediately by creating Terraform configuration files.
No configuration files found!
```
As I understood from the code it happens [here](https://github.com/ljfranklin/terraform-resource/blob/8e9b6faa4a3e6a0b463fcb70066fc70a9e9ed651/src/terraform-resource/terraform/client.go#L231)

**Comment by ljfranklin** [comment]
@beyhan could you link to a pipeline.yml that shows the error? Is this happening on a `get` or a `put` to the Terraform resource? Is the directory specified by `put.params.terraform_source` actually empty?

**Comment by ljfranklin** [comment]
@beyhan Oh, missed your second link. Is your pipeline specifying a remote URL like `github.com/org/ci//terraform/openstack` as `terraform_source`?

**Comment by beyhan** [comment]
Hi @ljfranklin ,

yes, we specifying such a terraform source. Here the [link](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/cf078f89c35dd1b20f31bc907b7571b8bbc3690e/ci/pipeline.yml#L686) to the `pipeline.yml` and the line inside where we specify the link.

**Comment by ljfranklin** [comment]
@beyhan Yeah, I was aware of this breaking change. Honestly I'm kind of glad though. Having terraform fetch the remote sources was something I regretted showing in the resource docs as it feels a bit "un-concourse" like in hindsight. Concourse wants you to pull things down with `get`s so you can pin to versions, used passed constraints, stuff like that. Using the remote source steps around the concourse way of doing things.

Do you have a strong use-case for preferring `source.terraform_source` or could you convert your pipeline to:

 ```
- get: bosh-openstack-cpi-release
...
- put: terraform
   params:
     terraform_source: bosh-openstack-cpi-release/ci/terraform/ci/bats-manual
```

Apologies for catching you off guard, I don't have a good way of notifying resource users that a change in Terraform might break them.

**Comment by beyhan** [comment]
@ljfranklin Thanks! We will try your suggestion. It sounds good an you are right it makes more sense in concourse world.

**Comment by Kiemes** [comment]
Also this reduces the number of terraform resources in our [pipeline](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/blob/cf078f89c35dd1b20f31bc907b7571b8bbc3690e/ci/pipeline.yml#L655-L686) to one. I also like the change.

**Comment by ljfranklin** [comment]
Going to close this out as it seems like the change is acceptable. Feel free to re-open if you run into more issues.
