### ISSUE TITLE
Support tfstate manipulations

### ISSUE THREAD

**Issue by gberche-orange** [ljfranklin/terraform-resource#41]
There are some TF usage that require TF state manipulations, such as terraform modules renaming ( https://ryaneschinger.com/blog/terraform-state-move/ provides more background and example of this use-case)

The state command enables CI/CD to perform automated manipulation of the state file (e.g. resource renaming): https://www.terraform.io/docs/commands/state/index.html

As an analogy, this is similar to database refactoring automation such as https://flywaydb.org/documentation/migration/ that enables continous deployment of applications requiring database schema manipulations.

It would be great to be able to specify some state management commands that the terraform-resource could apply (tracking their invocations and generally their lifecycle).

**Comment by ljfranklin** [comment]
@gberche-orange could you share how you envision this working in a pipeline config? My initial impression is that state file refactorings seem like a one-off thing, so you'd create a new "refactor" CI job, run it once for each env, then delete the job. Creating this job seems like the same amount of manual effort as it would take to modify each state file directly with the CLI unless you have a large amount of environments. Were you thinking of a different workflow?

**Comment by gberche-orange** [comment]
@ljfranklin yes a state file refactoring is associated with a terraform config change, and gets applied once.

We have the use case that terraform configs be provided by one owner/repo and multiple users apply them on their environments, possibly with different upgrade paths (e.g environment A chooses to go through versions 1.1, 1.2, 1.3, and 2.0 while environment B chooses to go through versions 1.1 and 2.0)

Adding state file refactoring support to the concourse resource enables terraform config owners to ship their refactoring files along with the terraform spec changes, freeing terraform config users from manually reading release notes to apply them manually using a CLI, or set up an explicit one off pipeline job.

Another benefit of builtin support in the `terraform-resource` w.r.t. to having an explicit custom pipeline job to apply state file manipulations, is that this builds upon the existing terraform-related logic and configurations (such as the terraform binary version, path to state file, future remote backend config,  etc...) that gets shared/tested in the community.

In terms of workflow, the state file refactoring step within the `terraform-resource` PUT would be continuously tracking for new refactoring scripts yet to apply and run them once in proper order (e.g. lexical order of their file name).

In terms of implementation, there is a need track history of previously applied refactoring scripts in order to not reapply them. One idea could be to model refactoring script executions as a terraform module tracked within a distinct tfstate file.

**Comment by ljfranklin** [comment]
In general I like to think of this resource as a thin wrapper around the Terraform CLI. While a Rails-style migration path that checks which migrations have already been applied sounds neat, it seems like a lot of complexity to add to this resource.

I'd feel more comfortable if this was a first-class feature in Terraform that this resource could leverage. Have you opened an issue on Terraform to see if this is a workflow that is on their radar?

**Comment by ljfranklin** [comment]
@gberche-orange this is a interesting idea but I'm going to close this as won't fix for now. If the Terraform CLI adds support for "migrations" I'll be happy to support that flow in this resource, but I feel that this resource is the wrong place to add the migration tooling due to its complexity and divergence from usual Terraform workflows.

**Comment by gberche-orange** [comment]
@ljfranklin I had polled the TF community on the future migration support on the [google group](https://groups.google.com/forum/#!searchin/terraform-tool/berche%7Csort:date/terraform-tool/5uVf4xGLGAU/jGlTD56cAgAJ) without response so far. I suspect such support would come into the terraform enterprise beta feature set along with [automatic terraform applies](https://www.terraform.io/docs/enterprise/runs/automatic-applies.html) feature set. I'll try to get confirmation by core contributors with a properly worded issue on the TF repo.

That would be useful to see if the `terraform-resource` would like to incrementally support some of the CI/CD features sets otherwise covered into terraform enterprise beta or other vendor products, or would rather stick to thin layer on the TF OSS CLI feature set. 

For the latter case, it would be useful to see what `terraform-resource`'s extensions points enable 3rd parties to add such features ontop of it, and avoid fully forking/diverging from it.

**Comment by ljfranklin** [comment]
I can keep this open for a bit since you're still digging. The main issue I have is adding more stateful behavior to the resource such as keeping track of which migrations have run. Since I'm trying to move towards using the built-in Terraform backends to store state, there isn't anywhere to really store arbitrary persistent metadata going forward unless you can somehow bake it into the statefile.

If you came up with a workflow that wasn't stateful I'd be more open to it. Maybe adding a flag to `terraform state mv` that makes it no-op on subsequent runs. Or you could do a `get` with `output_statefile` to pull down an existing statefile, pass it to some shared task to make the renames, then we could add a `put` param `update_statefile` that takes the path to the updated statefile rather than doing an apply.

**Comment by gberche-orange** [comment]
> I can keep this open for a bit since you're still digging. 

thanks! 

> Since I'm trying to move towards using the built-in Terraform backends to store state, there isn't anywhere to really store arbitrary persistent metadata going forward unless you can somehow bake it into the statefile.

My initial idea for a 1st class support into `terraform-resource` was to track execution of migrations into a distinct state file (also using default TF backend). This would mean model migration as terraform config (such as modules), with possibly the [local-exec](https://www.terraform.io/docs/provisioners/local-exec.html ) provisionner invoking the "terraform state move" migration commands.

> Or you could do a get with output_statefile to pull down an existing statefile, pass it to some shared task to make the renames, then we could add a put param update_statefile that takes the path to the updated statefile rather than doing an apply.

Quite promising. 

I can prototype a migration syntax on terraform-config. and see how this could fit it the workflow above.

**Comment by ljfranklin** [comment]
Going to close this out as while I think the migration idea is interesting, I still don't think such a feature belongs in this resource. Thanks for sharing your thoughts though!
