### ISSUE TITLE
How to lock the terraform provider version

### ISSUE THREAD

**Issue by bingosummer** [ljfranklin/terraform-resource#43]
When the terraform provider made a breaking change of the template, the template has to be updated.
However, sometime, I can't change the template in a short time.
So, is it possible to lock the provider/plugin version? Thanks

It seems that it always fetches the latest plugins.
https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/terraform/client.go#L230-L243

**Comment by ljfranklin** [comment]
@bingosummer I think the recommended way to lock down the provider version is to specify a `version` key in your configuration file as described [here](https://www.terraform.io/docs/configuration/providers.html#provider-versions). Would that work for you?

**Comment by ljfranklin** [comment]
@bingosummer just merged a PR to allow you to specify a custom plugin dir: https://github.com/ljfranklin/terraform-resource/pull/45. Between that and being able to specify a provider version constraint as described [here](https://www.terraform.io/docs/configuration/providers.html#provider-versions), I think you have several options for locking down the provider version with this resource.

I'm going to close this out for now but please re-open if I missed something.
