### ISSUE TITLE
Support for  Google Cloud Platform

### ISSUE THREAD

**Issue by divyabhargov** [ljfranklin/terraform-resource#46]
We have been using this to spin instances on AWS and it works great. We now want the ability to do the same on GCP. Wanted to run this by you to understand your thoughts. Are there any plans to support this for GCP ?

Do you see the changes required to support GCP as trivial ?

**Comment by ljfranklin** [comment]
@divyabhargov you can use Google Cloud Storage in [Interoperability Mode](https://cloud.google.com/storage/docs/interoperability) and set `storage.endpoint` to `storage.googleapis.com` to store state files in GCS.

In the near-term, I'm working on an update to use built-in Terraform Backends to store state. This should allow you use to s3, gcs, and many other backends to store the state files. You can follow along with this work here: https://github.com/ljfranklin/terraform-resource/issues/39.

**Comment by ljfranklin** [comment]
Closing this out after in-person convo. Nothing about this resource is specific to AWS other that storing state files on S3-compatible blobstores. You can absolutely use non-AWS providers like [GCP](https://www.terraform.io/docs/providers/google/index.html) with this resource.
