### ISSUE TITLE
TF_LOG: TRACE bug

### ISSUE THREAD

**Issue by bruxelles86** [ljfranklin/terraform-resource#47]
Hi there.

We've been using your Terraform concourse resource - great tool, thanks! - and have stumbled upon a bug. In some circumstances, `put`-ing a Terraform resource will lead to the following console output when TF_LOG is set to TRACE in the resource definition:

```2017/11/28 16:47:13 Failed to unmarshal JSON output.
16:47:13
Error: invalid character '/' after top-level value
16:47:13
Output: 2017/11/28 16:47:13 [INFO] Terraform version: 0.11.0  ec9d4f1d0f90e8ec5148f94b6d634eb542a4f0ce+CHANGES
16:47:13
2017/11/28 16:47:13 [INFO] Go runtime version: go1.9
16:47:13
2017/11/28 16:47:13 [INFO] CLI args: []string{"/usr/local/bin/terraform", "output", "-json", "-state=/tmp/terraform-resource-out665328595/terraform.tfstate"}
16:47:13
2017/11/28 16:47:13 [DEBUG] Attempting to open CLI config file: ~/.terraformrc
16:47:13
2017/11/28 16:47:13 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
16:47:13
2017/11/28 16:47:13 [INFO] CLI command args: []string{"output", "-json", "-state=/tmp/terraform-resource-out665328595/terraform.tfstate"}
```

A colleague of ours, who encountered the same issue a while ago, eventually rescued us, and said he believed the problem was caused by the logs being sent to STDOUT while another part of the resource was already watching STDIN for something else.

Just thought I'd flag it for you.

**Comment by ljfranklin** [comment]
@bruxelles86 correct, Concourse requires that resources only emit valid JSON data over STDOUT, all debug information must go to STDERR. The Terraform docs indicate that TF_TRACE should only go to STDERR, maybe there is a rogue log line in Terraform CLI that is going to STDOUT instead?

Also have you seen this error in the last 20 days or so? I ask because I recently fixed an intermittent bug that manifested with the same error: https://github.com/ljfranklin/terraform-resource/issues/44.

**Comment by ljfranklin** [comment]
Nevermind, I'm incorrectly capturing stderr when parsing for outputs: https://github.com/ljfranklin/terraform-resource/blob/b0009fac306fa8ee09e964f0a0bfc48a18f99b83/src/terraform-resource/terraform/client.go#L126. Thanks for the heads up, I'll try to get this fixed in the next day or so.

**Comment by ljfranklin** [comment]
Moving through CI now, I'll close this out once the fix is present in the docker image

**Comment by bruxelles86** [comment]
Great stuff - thank you!

**Comment by ljfranklin** [comment]
@bruxelles86 this should be fixed in the `latest` image. Give it a try and re-open if you still see issues.

**Comment by bruxelles86** [comment]
Just ran the pipeline in the same state it was in when we raised this, and now it's working fine - thanks!
