### ISSUE TITLE
Resource should include `bash` to be more consistent with other resources

### ISSUE THREAD

**Issue by cunnie** [ljfranklin/terraform-resource#5]
When hijacking into a container, it's not obvious that you'd need to explicitly pass `/bin/sh` as the resource doesn't include `bash`:

```bash
fly -t env i -j your-pipeline/terraform-get /bin/sh
```

**Comment by ljfranklin** [comment]
Fixed in caf8da6980b7c0eadc137d664d8f6d127813831b
