### ISSUE TITLE
Proxy from envs is ignored by client

### ISSUE THREAD

**Issue by asehra** [ljfranklin/terraform-resource#52]
The terraform cli wrapper in client currently [builds the Envs from scratch](https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/terraform/client.go#L220-L223), picking up only the `PATH` env var. Should this take the current environment (`os.Environ`) as the starting point before adding more environment variables? 

We're specifying the proxy details using the `http_proxy`, `https_proxy` and `no_proxy`, without which terraform won't be able to speak to hashicorp or the iaas.

**Comment by ljfranklin** [comment]
@asehra whoops, oversight on my part. The fix should be present in the `ljfranklin/terraform-resource:latest` image now. Please give it a spin and let me know if you run into more issues.

**Comment by asehra** [comment]
I've checked it and it works! Thanks a lot.
