### ISSUE TITLE
var_files cannot include maps

### ISSUE THREAD

**Issue by wendorf** [ljfranklin/terraform-resource#57]
If I pass a var_file:

```
my_map:
  a: b
  c: d
```

the resulting args will be: `-var 'my_map={}'`

This is because terraform/client.go's `formatVar` function, in the `reflect.Map` case, casts value as `value.(map[string]interface{})`, which is always an empty map. If this is switched to a map from interface to interface, the resulting args will be: `-var 'my_map={a="b",c="d"}'`. However, making this change breaks maps passed as `vars` in the exact same way. In other words, `value.(map[string]interface{})` works for `vars`, and `value.(map[interface{}]interface{})` works for `var_files`.

Because of this, I'm not quite sure what the correct fix is. If you have some guidance here, I can submit a PR. Thanks!

**Comment by ljfranklin** [comment]
Hey @wendorf! These two issues around maps are showing that the `-var` approach is a bit brittle. And if you do quote or escape something wrong, the resource often prints your credential to the screen in the error which isn't great. I'm thinking of ditching the `-var` flag for the `-var-file` flag and writing all the creds to temporary files to sidestep this issue. I'll try to take a closer look at this in the next few days.

**Comment by wendorf** [comment]
That would be great! Thanks! Let me know if there's anything I can do to help.

**Comment by dvianello** [comment]
Badly affected by this at the moment - any help we can provide, just ask!

**Comment by dvianello** [comment]
As a side note, do you think that the new version of the resource will also be able to support native `*.tfvars` files, simply specified via a path directly? 

That would provide a nice escape hatch in case of problems, and - in our particular case - avoid duplication of code between `.tfvars` files we use when deploying locally and json files we'd need to write for this resource. I do find the `tfvars` format more readable than json...

**Comment by ljfranklin** [comment]
@wendorf this should be fixed on both the `latest` and `backend-beta` images. Give it a spin and let me know if you're still running into issues.

**Comment by ljfranklin** [comment]
@dvianello as part of this fix I also added support for `var_files` in HCL format like normal `.tfvars` files. Just make sure your var filename ends with `.tfvars` which is what tells the resource to use the HCL parser.

**Comment by ljfranklin** [comment]
Closing this out but please re-open if I missed something.

**Comment by wendorf** [comment]
Thank you kindly! Looking forward to testing it out.

**Comment by wendorf** [comment]
This worked great for us! As a caution, the fix _does_ change the behavior for anyone who already has workarounds. e.g. if you had this YAML:

```
my_map:
  "\"key-one\"": value
```

The old version of the terraform-resource would set the `key-one` key to `value`, but now it sets the `"key-one"` key to `value` and will unset the `key-one` key. This can cause errors for people who consume the new version without fixing their variables. Might want to do something like a major version bump here? Don't know.

At any rate, thank you for fixing this!
