### ISSUE TITLE
map keys cannot include special characters

### ISSUE THREAD

**Issue by wendorf** [ljfranklin/terraform-resource#58]
If I specify:

```
vars:
  domains:
    "*.example.com": my-favorite-domain
```

I generate the args: `-var 'domains={*.example.com="my-favorite-domain"}'` and Terraform throws the error:

`invalid value "domains={*.example.com=\"my-favorite-domain\"}" for flag -var: Cannot parse value for variable ("{*.example.com=\"my-favorite-domain\"}") as valid HCL: At 1:6: illegal char`

To resolve this, I must escape the key myself:

```
vars:
  domains:
    "\"*.example.com\"": my-favorite-domain
```

to generate the args: `-var 'domains={"*.example.com"="my-favorite-domain"}'`

**Comment by ljfranklin** [comment]
Rolling this issue into https://github.com/ljfranklin/terraform-resource/issues/57
