### ISSUE TITLE
plan_run should require a source

### ISSUE THREAD

**Issue by ntbrittain** [ljfranklin/terraform-resource#62]
Regarding the logic at: https://github.com/ljfranklin/terraform-resource/blob/b1023a2d0ee8bce92ae3fd577882f47beec8ba2f/src/terraform-resource/out/out.go#L60

PlanRun currently does not require a source config, presumable because the source for the Apply step is the plan. However, the apply step still runs the terraform init step, when PlanRun is true, and the init step can not run against a plan, it requires a source.

**Comment by ljfranklin** [comment]
@ntbrittain another good find! That `if` statement was a holdover from [earlier days](https://github.com/ljfranklin/terraform-resource/blob/688c9e9783641bd6413f694619a6e149ca066a84/src/terraform-resource/terraform/client.go#L30-L31) when terraform providers were bundled in with the terraform CLI and you didn't have to run `init` to apply a plan. Removed the `terraformModel.PlanRun == false` check here: https://github.com/ljfranklin/terraform-resource/commit/91574b7ab1d04964bbe560d5d61c525c44461117.
