### ISSUE TITLE
Question: how are workspaces used in the beta backend? 

### ISSUE THREAD

**Issue by dvianello** [ljfranklin/terraform-resource#64]
Hi there,

looking around the code for the beta backend, I noticed you're using workspaces to deal with the different environments. 

Hashicorp discourages using different workspaces to separate dev/staging/production deployment since they don't offer a strong enough isolation. We adhere to this, and I was wondering in which cases the `beta` resource ends up using `workspaces` vs completely separated state files.

Thanks for the brilliant work! 

Dario

**Comment by dvianello** [comment]
Also, what is the new `serial`?

**Comment by ljfranklin** [comment]
@dvianello I'm guessing you're referring to [this doc](https://www.terraform.io/docs/state/workspaces.html#when-to-use-multiple-workspaces) which states:

> When Terraform is used to manage larger systems, teams should use multiple separate Terraform configurations that correspond with suitable architectural boundaries within the system so that different components can be managed separately and, if appropriate, by distinct teams. Workspaces alone are not a suitable tool for system decomposition, because each subsystem should have its own separate configuration and backend, and will thus have its own distinct set of workspaces.

The terraform-resource does use workspaces under the hood to manage environment state files as the resource needs a way to list/download/upload all the state files under a given backend config. But it's up to you to decide whether all the environments are stored using the same backend config or whether you use separate backend configs for each environment. For example, a single pipeline might have a `terraform-staging` resource of `type: terraform` which has `backend_config.bucket: staging` and another resource called `terraform-prod` which has `backend_config.bucket: prod`. This way your state files are totally isolated in different backends. Alternatively, you could declare a single terraform resource and the resource would but all your state files in the same backend, it's up to you. I most frequently use the resource to manage a large pool of testing envs in CI, so a single backend with many workspaces works well for that use case.

> Also, what is the new `serial`?

I don't know what you mean by `serial`. Can you give a link to the feature you're talking about?

**Comment by ljfranklin** [comment]
Oh, I forgot I started using the `serial` number from the state file in the resource metadata. It's a number that gets incremented every time the state file changes. See [docs](https://www.terraform.io/docs/backends/state.html#manual-state-pull-push).

**Comment by dvianello** [comment]
Hi @ljfranklin, 

thanks for all the answers! I guess that using a different `backend_config.key` instead of `backend_config.bucket` would do as well to avoid workspaces. 

We unfortunately had to drop using this resource because of a string requirement to use IAM instance profiles & being able to `plan` before `apply` in pre-prod/prod environments. We'll gladly jump back on it when `plan` will be available again! 

TBH, the resourse autonomously updating the plan to s3 also in the `beta-backend` waiting for that TF bug to closed would be a brilliant stopgap! Of course supporting IAM creds ;-)

Thanks again for this brilliant resource!
