### ISSUE TITLE
Populate the `name` file on `get` even when `action: destroy`

### ISSUE THREAD

**Issue by chendrix** [ljfranklin/terraform-resource#65]
If you accidentally delete a `terraform.tfstate.tainted` file, you can no longer run a `get` of the terraform resource. 

You might want to run a `get` of the resource with `action: destroy` so that you can populate the name of the resource and retry destroying using something other than `put: {action: destroy}`, e.g. using https://github.com/genevieve/leftovers

**Comment by ljfranklin** [comment]
Thanks @chendrix, this change should now be available in the `latest` resource image!
