### ISSUE TITLE
Choose destination directory for a terraform override file

### ISSUE THREAD

**Issue by genevieve** [ljfranklin/terraform-resource#71]
All terraform override files provided in the configuration of the resource are destined for the `terraform-source` directory. With the new configuration of the terraforming-* repos, the "root" templates (ex: pas) are now in a separate module than other modules (ex: isolation-segment). 

If it it would be possible to have the default behavior copy the override files to the source directory, and introduce the ability to specify a different destination directory for a particular override file.

**Comment by ljfranklin** [comment]
Yeah, that was an oversight on my part. Maybe we add a new `module_override_files` key:

```
module_override_files:
- src: pcf-releng-ci/some-ops-file.tf
  dest: terraforming-gcp/pas/
```

Going to mark this as `help wanted` in case anyone wants to take a try at a PR.

**Comment by ljfranklin** [comment]
Closed via https://github.com/ljfranklin/terraform-resource/pull/75
