### ISSUE TITLE
terraform plan/ apply fails, if recent terraform output objects consist of an empty list []

### ISSUE THREAD

**Issue by tangerstein** [ljfranklin/terraform-resource#77]
Hi :)
I faced a problem when using the terraform-resource and defining outputs in the terraform scripts which result in an empty list:
e.g. smth. like:
`snapshots = [[snap-0, snap-1],[]]`
This output is inserted into the vars-file[randomID] when executing a second pipeline build. The empty list [] is now interpreted as empty JSON array and the var-file is invalid. 

I assume, we should somehow escape the brackets

**Comment by ljfranklin** [comment]
Does your vars-filename end in `.tfvars` or something else? If it ends in `.tfvars` the output is passed to Terraform CLI unmodified, else the resource tries to read in the vars file as YAML/JSON.

**Comment by tangerstein** [comment]
Hi 😊,
I mean the var file, which is generated by the terraform-resource plugin itself. I did not modify the file in any kind. I only defined some terraform outputs, which somehow were included in the particular generated log file. I assume there is something going wrong with the generation of this var file.

**Comment by ljfranklin** [comment]
Oh, I have seen this before. The resource "feature" of feeding the outputs of the previous `put` back in as inputs to the next was a mistake as it can causing confusing failures like this. From the README: "If a state file already exists, the outputs will be fed back in as input vars to subsequent puts with the lowest precedence". The workaround is to set an input var on the second `put` to nil it out:

```
put: terraform
params:
  vars:
    snapshots: nil
...
```

I'm planning on dropping this surprising behavior in some future release of the resource.

**Comment by tangerstein** [comment]
Ok, thanks for knowing, this exactly was the workaround, which I've currently in use :) I'm looking forward for the update 👍👍

**Comment by ljfranklin** [comment]
Just merged a branch of work into `master` which adds a new `backend_config` field that replaces the `storage` field. When backends are used this functionality no longer applies: "If a state file already exists, the outputs will be fed back in as input vars to subsequent puts with the lowest precedence". This is noted as a breaking change [here](https://github.com/ljfranklin/terraform-resource#backend-migration). I think that covers this issue but feel free to re-open if I missed something.
