### ISSUE TITLE
`env_name` could be optional

### ISSUE THREAD

**Issue by benjvi** [ljfranklin/terraform-resource#78]
I often seem to forget to configure env_name in all the places I need to, and I rarely make use of workspaces.

Would you be open to a PR to give it a fallback value of `default` (and maybe also to allow specifying it as `workspace`), at least for the `beta-backend` branch?

**Comment by ljfranklin** [comment]
@benjvi I'm hesitant to add a default value as I could see some users accidentally deleting a bunch of resources by using the same backend config in multiple pipelines but forgetting to specify a different `env_name`. I have been thinking about changing `env_name` to `workspace` or similar to make its usage more clear, haven't decided whether it's worth forcing users to update a bunch of template though.

**Comment by ljfranklin** [comment]
I think for now I'm going to close this as `won't fix`. Although renaming `env_name` to `workspace` is somewhat appealing I don't feel like it's worth introducing a breaking change at this time. It would be nice if the Terraform CLI itself injected `workspace_name` or similar as a built-in template variable to at least make templates more portable, but that would have to be a new issue open on the Terraform project. Closing this out for now but feel free to add additional comments.
