### ISSUE TITLE
Backend Migration fails with `Workspace "foo" already exists

### ISSUE THREAD

**Issue by saedalavinia** [ljfranklin/terraform-resource#80]
Figured it's better to have this as a separate issue. 

I am wondering if this been tested with `env_name` ?  

My migration failing with: 
```sh
2019/03/25 14:19:53 Apply Error: Error running `workspace new -state`: exit status 1, Output: Workspace "foo" already exists
```

**Comment by ljfranklin** [comment]
Going to close this one out as I suspect this is a side-effect of the events described here: https://github.com/ljfranklin/terraform-resource/issues/79#issuecomment-476380317
