### ISSUE TITLE
migrated_from_storage does not copy override files into terraform source when running with plan_only: true

### ISSUE THREAD

**Issue by ebrusseau** [ljfranklin/terraform-resource#82]
In the legacy storage action you copy the override files to the source in the setup() function, and in the migrated storage action you are copying in attemptApply, but not in setup(), so they are missing when Plan() is run!

_Originally posted by @ebrusseau in https://github.com/ljfranklin/terraform-resource/issues/81#issuecomment-480910512_

**Comment by ljfranklin** [comment]
@ebrusseau thanks for being a guinea pig on testing this plan flow with backends. Added the override file copying here: https://github.com/ljfranklin/terraform-resource/commit/9abfe139afc2a21a76916ce12a43e7181cca6369. This change is now present in the `latest` image. Give it one more try and let me know if you're still seeing issues.

**Comment by ebrusseau** [comment]
@ljfranklin Looks good as far as this bug is concerned! I'm seeing issues where the resource not fetched when there is no previous history (e.g. new pipeline that has never been run before) but I'll file that separately after I investigate.
