### ISSUE TITLE
env_name: mismatch between documentation and actual behaviour

### ISSUE THREAD

**Issue by iuriaranda** [ljfranklin/terraform-resource#85]
According to the documentation:

> Note: You must specify one of the following options: source.env_name, put.params.env_name, put.params.generate_random_name, or env_name_file

But I think the actual behaviour is slightly different, as the `EnvName()` function ignores the `source.env_name` parameter: https://github.com/ljfranklin/terraform-resource/blob/master/src/terraform-resource/out/env_namer.go#L44
It only considers `put.params.env_name`, `put.params.env_name_file`, or `put.params.generate_random_name`.

That raises an error if you just specify a default `env_name` at the source level and not in every put and get.

```
2019/03/29 12:56:00 Failed to create env name: Must specify `put.params.env_name`, `put.params.env_name_file`, or `put.params.generate_random_name`
```

Is the behaviour intended for some reason and the documentation is incorrect? Or the other way around?

It would be quite useful for us to be able to specify a default `env_name` at the source level without the need to specify it on every `get` and `put`.

**Comment by ljfranklin** [comment]
@iuriaranda whoops, the intent was for definitely for `source.env_name` to work. Not sure when that regression was introduced. This fix should be present in the `latest` image now: https://github.com/ljfranklin/terraform-resource/commit/f017628c090f185d01afda2630b299dac7aa3a97.

**Comment by iuriaranda** [comment]
@ljfranklin great! Thanks for your time and effort 🙂
