### ISSUE TITLE
check fails to pull version if env_name is not supplied and using backend

### ISSUE THREAD

**Issue by ebrusseau** [ljfranklin/terraform-resource#86]
When running with a new pipeline (e.g. terraform resource has no prior history), the check fails to pull a version if configured with new backend and no source.env_name is provided. There is no error, it just does nothing.

When I migrated the settings on a pipeline that did have history, this was not a problem.

**Comment by ljfranklin** [comment]
@ebrusseau this is a known limitation, although I don't know if it's listed in the README: https://github.com/ljfranklin/terraform-resource/blob/7ff97166c4393142acc34df0b8e20432d3535602/src/terraform-resource/check/check.go#L27-L29. Is this causing any issues? The first time you run a `put` it will show up in the resource history view.

**Comment by ebrusseau** [comment]
> @ebrusseau this is a known limitation, although I don't know if it's listed in the README:
> 
> [terraform-resource/src/terraform-resource/check/check.go](https://github.com/ljfranklin/terraform-resource/blob/7ff97166c4393142acc34df0b8e20432d3535602/src/terraform-resource/check/check.go#L27-L29)
> Lines 27 to 29 in [7ff9716](/ljfranklin/terraform-resource/commit/7ff97166c4393142acc34df0b8e20432d3535602)
>  // Triggering on new versions is only supported in single-env mode: 
>  // - expensive to check for changes across all statefiles 
>  // - triggering on changes to any environment doesn't seem very useful 
> . Is this causing any issues? The first time you run a `put` it will show up in the resource history view.

Yes this causes issues as even when a pipeline job is not set to trigger off this resource, it will still sit stuck waiting for versions of this resource if it’s used - which in my case it is.

**Comment by ljfranklin** [comment]
@ebrusseau So you have a pipeline that has a `put` job which creates the versions and other `get` jobs which pull the output, but you're not able to run the `put` just yet (or something like that)? If so, I think you can run `fly -t TARGET check-resource -r PIPELINE_NAME/RESOURCE_NAME --from 'env_name:YOUR_ENV_NAME'` to manually force a check against that env.

**Comment by ebrusseau** [comment]
> @ebrusseau So you have a pipeline that has a `put` job which creates the versions and other `get` jobs which pull the output, but you're not able to run the `put` just yet (or something like that)? If so, I think you can run `fly -t TARGET check-resource -r PIPELINE_NAME/RESOURCE_NAME --from 'env_name:YOUR_ENV_NAME'` to manually force a check against that env.

I will close this for now, as there is a workaround
