### ISSUE TITLE
Deleting workspace with Terraform apply

### ISSUE THREAD

**Issue by mdharamadas1** [ljfranklin/terraform-resource#92]
I don't understand why the resource is trying to delete workspace after `terraform apply` when `plan_run` is called? Is there a way to skip it?

I get following error as my S3 bucket policy do not allow `DeleteObject` action.

```
Failed To Run Terraform Apply!
2019/06/20 16:13:26 Apply Error: Error running `workspace delete -force`: exit status 1, Output: AccessDenied: Access Denied
	status code: 403, request id: B4E7527FD40637CA, host id: ga+A5Sv0og3mkdu8w81QdOc5roCQ3kJ9pFgGisDWWo5fBRsxwGSd90XxI4wcvL+lAUg0mY5sbZg=
```

Also I see following desc for `plan_run`, what does `...then delete it.` mean?

`plan_run: Optional. Default false This boolean will allow Terraform to execute the plan file stored on the configured backend, then delete it.`

**Comment by ljfranklin** [comment]
The plan file handling is unfortunately a bit of a hack. See the [Terraform docs](https://www.terraform.io/docs/commands/plan.html) for a description of generating this file via the `plan -out` flag. The approach to saving the plan file in the resource is described [here](https://github.com/ljfranklin/terraform-resource/issues/39#issuecomment-452089037). When you generate a plan via `plan_only` the resource stores the plan file in your configured backend alongside your statefiles. When you later run a job with `plan_run`, on success the resource tries to delete the plan file and the temporary plan workspace from the backend as it is no longer needed.

To get around this you'll have to add a delete exception in your S3 policy for files and directories ending in `-plan` ([code](https://github.com/ljfranklin/terraform-resource/blob/858f80099de92625f0bd9fac2d3beccca2a5dd58/src/terraform-resource/terraform/action.go#L339)). I might consider accepting a PR to allow skipping the plan deletion but as plan files can contain [credentials](https://www.terraform.io/docs/commands/plan.html#security-warning) I would strongly recommend deleting them once they are no longer needed.

**Comment by mdharamadas1** [comment]
OK, that make sense but making deletion implicit is my concern, we should probably convert it to explicit step instead. I would love to do a PR but I have no experience on GO (yet!).
Meantime, I think we will try a delete exception in policy I guess. Thanks for the detailed explanation!
