### ISSUE TITLE
Hiding sensitive information from plan/apply output

### ISSUE THREAD

**Issue by tareks** [ljfranklin/terraform-resource#95]
This may be slightly related to #28. 

When passing variables or parameters to various terraform resources (`aws_lambda_function` from the aws provider in my case), some of the information may be sensitive and may include secrets. Is there a recommended way to mask any such output or even suppress it, if required so it doesn't get printed/logged in concourse?

More concrete example involves something like this:

```
resource "aws_lambda_function" "test_lambda" {
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = "${aws_iam_role.iam_for_lambda.arn}"
  handler       = "exports.test"

  # The filebase64sha256() function is available in Terraform 0.11.12 and later
  # For Terraform 0.11.11 and earlier, use the base64sha256() function and the file() function:
  # source_code_hash = "${base64sha256(file("lambda_function_payload.zip"))}"
  source_code_hash = "${filebase64sha256("lambda_function_payload.zip")}"

  runtime = "nodejs8.10"

  environment {
    variables = {
      SECRET = "{var.secret_passed_by_concourse_resource}"
    }
  }
}
```

The terraform resource would then have something like:
```
 - put: terraform
    params:
      terraform_source: source/terraform
      plan_run: false 
      vars:
          secret_passed_by_concourse_resource: ((secret))
```

The result is that when plan/apply steps are executed, the secret is printed in clear text. Is there a way to hide/mask this output or a better way of managing this sort of secret handling without pulling the secret from within the lambda itself?

**Comment by ljfranklin** [comment]
Sounds like an issue with the Terraform AWS provider, I don't think there's anything that can be done at the resource level. Similar to marking outputs as `sensitive`, provider authors can also mark resource parameters as `sensitive` so they are redacted in STDOUT, e.g. [here](https://github.com/terraform-providers/terraform-provider-aws/blob/5f5994c03f59cf93d3a456403c09f793944f2870/aws/resource_aws_kms_ciphertext.go#L25). You'll have to open an issue or PR to mark the `environment.variables` field as `sensitive` [here](https://github.com/terraform-providers/terraform-provider-aws/blob/5f5994c03f59cf93d3a456403c09f793944f2870/aws/resource_aws_lambda_function.go#L227-L229).

 As I'm not aware of any workarounds for hiding that secret from the resource, I'm going to close this out. Feel free to re-open if opening an issue on the provider uncovers some workaround.
