### ISSUE TITLE
map(map) being parsed into map(list)

### ISSUE THREAD

**Issue by ghost** [ljfranklin/terraform-resource#98]
I have a `tfvars` file in HCL format getting merged/parsed incorrectly into JSON.  The same `tfvars` file works correctly in my local environment.
```
clusters = {
  staging = {
    ami_id  = "ami-xyz"
    enabled = true
  }
}
```

Variable definition:
```
variable clusters {
  type        = map(map(string))
  description = "Cluster Specific configurations"
}
```

Error in Concourse:
```
Error: Invalid value for input variable

  on /tmp/668228708vars-file.tfvars.json line 1:
   1: {"clusters":{"staging":[{"ami_id":"ami-xyz","enabled":true}]}}

The given value is not valid for variable "clusters": element "staging": map
of string required.
```

**Comment by ljfranklin** [comment]
@lc-od I'll try to get this fixed soon. Terraform 0.12 migrated to HCL2 which has better support for complex types like maps of maps. I'll need to update how the resource does the `vars`/`vars-file` merging to handle this.

In the meantime, you might be able to temporarily workaround the issue by changing `type = map(map(string))` to the more permissive HCL1 `type = "map"` (the quotes around "map" are required I think).

**Comment by ljfranklin** [comment]
Both the `latest` and 0.12.8` resource tags should support more complex HCL types now. Looks like whoever reported this deleted their account but someone else can feel free to re-open if they are still having issues.
